# Generated by Django 4.2.1 on 2023-06-21 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('local', '0001_initial'),
        ('estrutura', '0001_initial'),
        ('acervo', '0001_initial'),
        ('assunto', '0001_initial'),
        ('produtor', '0001_initial'),
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_inicial', models.DateTimeField()),
                ('data_final', models.DateTimeField()),
                ('info_adicionais', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('genero_documental', models.CharField(choices=[('1', 'Textrual'), ('2', 'Iconográfico'), ('3', 'Audiovisual'), ('4', 'Fonográfico'), ('5', 'Cartográfico'), ('6', '3D'), ('7', 'Multimeios')], default='1', max_length=1)),
                ('nivel_permissao', models.CharField(choices=[('1', 'Restrição total'), ('2', 'Exige autorização para visualização'), ('3', 'Livre para visualização, restrito para download'), ('4', 'Livre total')], default='1', max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('acervo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acervo', to='acervo.acervo')),
            ],
            options={
                'verbose_name_plural': 'Documentos',
                'db_table': 'documento',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoProdutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.documento')),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtor.produtor')),
            ],
            options={
                'verbose_name_plural': 'DocumentosProdutores',
                'db_table': 'documento_produtor',
                'ordering': ['produtor'],
                'unique_together': {('produtor', 'documento')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.documento')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.pessoa')),
            ],
            options={
                'verbose_name_plural': 'DocumentosPessoas',
                'db_table': 'documento_pessoa',
                'ordering': ['pessoa'],
                'unique_together': {('pessoa', 'documento')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoAssunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assunto.assunto')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.documento')),
            ],
            options={
                'verbose_name_plural': 'DocumentosAssuntos',
                'db_table': 'documento_assunto',
                'ordering': ['assunto'],
                'unique_together': {('assunto', 'documento')},
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='assunto',
            field=models.ManyToManyField(through='documento.DocumentoAssunto', to='assunto.assunto'),
        ),
        migrations.AddField(
            model_name='documento',
            name='estrutura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documento', to='estrutura.estrutura'),
        ),
        migrations.AddField(
            model_name='documento',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documento', to='local.local'),
        ),
        migrations.AddField(
            model_name='documento',
            name='pessoa',
            field=models.ManyToManyField(through='documento.DocumentoPessoa', to='pessoa.pessoa'),
        ),
        migrations.AddField(
            model_name='documento',
            name='produtor',
            field=models.ManyToManyField(through='documento.DocumentoProdutor', to='produtor.produtor'),
        ),
    ]
