# Generated by Django 4.2.1 on 2023-06-21 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('qualidade', models.CharField(choices=[('1', 'Baixa'), ('2', 'Media'), ('3', 'Alta')], default='1', max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objeto_digital', to='documento.documento')),
            ],
            options={
                'verbose_name_plural': 'ObjetosDigitais',
                'db_table': 'objetodigital',
                'ordering': ['codigo'],
            },
        ),
    ]
