# Generated by Django 4.2.1 on 2023-06-21 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('sigla', models.CharField(max_length=30, unique=True)),
                ('descricao', models.TextField()),
                ('info_adicionais', models.TextField(blank=True, null=True)),
                ('nivel', models.PositiveSmallIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('acervo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estrutura_acervo', to='acervo.acervo')),
                ('estrutura_nivel_superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nivel_superior', to='estrutura.estrutura')),
            ],
            options={
                'verbose_name_plural': 'Estruturas',
                'db_table': 'estrutura',
                'ordering': ['sigla'],
            },
        ),
    ]
